### ISSUE TITLE
Using 'stop' to mean 'restart'

### ISSUE THREAD

**Issue by redthor** [nickjj/deploy-web-apps-with-docker#3]
Hi @nickjj,

Quick question. In the unit files and in the git hooks you use `stop` to meant `restart`:

```
echo "Restarting nginx"
docker stop "nginx"
```

can you explain how this works? i.e. why stopping restarts a service?
thanks.

**Comment by nickjj** [comment]
The unit file is set up to automatically restart a container if it goes down. The act of stopping the container will trigger systemd to start it automatically. It's effectively restarting it.
