### ISSUE TITLE
Certs location

### ISSUE THREAD

**Issue by redthor** [nickjj/deploy-web-apps-with-docker#4]
In chapter 7 the output of the ssl key generation goes to `deploy/certs/rediscounter.key`:

```
ssl req \
-newkey rsa:2048 -nodes -sha256 -keyout \
deploy/certs/rediscounter.key \
-x509 -days 3650 -out deploy/certs/rediscounter.crt \
-subj "/C=US/ST=NewYork/L=NewYork/O=IT/CN=fakerediscounter.com"

```

but this repo has it at:

```
deploy/nginx/certs/rediscounter.key
```

and the Vagrantfile in chapter 8 needs it in the second location, so probably change chapter 7 snippet.

**Comment by nickjj** [comment]
Thanks a lot, that was an oversight. A new version of the book has been published which fixes chapter 7's command.

The Vagrantfile should be good as it copies it to the proper location on the server and is reading it from `deploy/nginx/certs`, if it ends up being an issue please open a new ticket specific to the Vagrantfile.
