### ISSUE TITLE
chapter 8 nginx config and site access

### ISSUE THREAD

**Issue by redthor** [nickjj/deploy-web-apps-with-docker#6]
Hi @nickjj 
Can you add some instructions to the book to access the staging server in chapter 8? i.e. should it be possible to access the site?

I see that the Vagrantfile defines `'80' => '8080'` and `'443' => '8081'` port mappings.

I've tried:

```
wget http://127.0.0.1:8080
--2015-11-19 21:28:16--  http://127.0.0.1:8080/
Connecting to 127.0.0.1:8080... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://127.0.0.1/ [following]
--2015-11-19 21:28:16--  https://127.0.0.1/
Connecting to 127.0.0.1:443... failed: Connection refused.
```

which is fair enough, the nginx conf redirects the user to `443` which is not in use because that's been mapped to `8081`.

However attempting to get to the SSL version via `8081` also gives me an error:

```
wget --no-check-certificate https://127.0.0.1:8081
--2015-11-19 21:24:29--  https://127.0.0.1:8081/
Connecting to 127.0.0.1:8081... connected.
WARNING: cannot verify 127.0.0.1's certificate, issued by '/C=US/ST=NewYork/L=NewYork/O=IT/CN=fakerediscounter.com’:
  Self-signed certificate encountered.
    WARNING: certificate common name 'fakerediscounter.com’ doesn't match requested host name '127.0.0.1’.
HTTP request sent, awaiting response... 502 Bad Gateway
2015-11-19 21:24:29 ERROR 502: Bad Gateway.
```

In CoreOS guest the nginx `journalctl` log is:

```
Nov 19 10:24:29 core-01 docker[957]: 2015/11/19 10:24:29 [error] 10#10: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: yourrealdomain.com, request: "GET / HTTP/1.1", upstream: "http://10.1.0.3:8000/", host: "127.0.0.1:8081"
Nov 19 10:24:29 core-01 docker[957]: 10.0.2.2 - - [19/Nov/2015:10:24:29 +0000] "GET / HTTP/1.1" 502 166 "-" "Wget/1.15 (linux-gnu)"
Nov 19 10:28:16 core-01 docker[957]: 10.0.2.2 - - [19/Nov/2015:10:28:16 +0000] "GET / HTTP/1.1" 307 180 "-" "Wget/1.15 (linux-gnu)"
```

**Comment by redthor** [comment]
Worked it out, this line needs to be `8080`:
https://github.com/nickjj/deploy-web-apps-with-docker/blob/master/chapter-8/deploy/nginx/configs/default.conf#L3

all good

**Comment by nickjj** [comment]
Hmm, line 3 of that config shouldn't need to be 8080. nginx is your gateway to the web app.

Vagrant is forwarding those ports because you can't listen on 80 and 443 without root so I forwarded them to something higher.

In your `Vagrantfile` do you have these values defined? https://github.com/nickjj/deploy-web-apps-with-docker/blob/master/chapter-9/deploy/nginx/docker-entrypoint#L7-L8

Also what happens if you goto the staging server's IP address directly without any ports, ex. `https://172.17.8.101`.

**Comment by redthor** [comment]
My `app.py` has port `8080` in it, so setting upstream to `8080` worked for me fine. I'm not sure how my `app.py` drifted away from yours (`8000`). Anyway it's fine thanks. Now onto the next chapter!
